# Generated by Django 4.2 on 2025-01-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_author_customuser_followings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="author",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
